name: main

on: [push]

jobs:
  main:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile

      # - run: bunx tsc

      - run: bun test

      - run: bunx vite build src --base ./ --outDir ../dist

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - uses: actions/deploy-pages@v4

      - uses: actions/upload-artifact@v4
        with:
          name: game
          path: dist
